### ISSUE TITLE
Error: No asset found for platform linux-amd64 when using castor-php/setup-castor@v0.1.0

### ISSUE THREAD

**Issue by gponty** [castor-php/setup-castor#16]
Hello,

I encountered an error when using the following GitHub Actions configuration:

```
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Setup Castor
    uses: castor-php/setup-castor@v0.1.0
```

Error Message:

`Error: No asset found for platform linux-amd64`

Is this issue coming from my script, or could it be a bug?

Thank you.
